import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="sidebar">
      <a href="#personaldetails">Personal Details</a>
      <a href="#summary">Summary</a>
      <a href="#techstack">Technologies</a>
      <a href="#projects">Projects</a>
      <a href="#education">Education</a>
      <a href="#certifications">Certifications</a>
      <a href="#workexperience">Work Experience</a>
    </div>

    <div className="counter">
      <h2>Visitor Counter</h2>
      <p>0</p>
    </div>

    <main className="main">
      <section className="header">
        <h1 className="text-3xl font-bold">Antonio Riccelli</h1>
        <h3>Full Stack Developer</h3>

        <address className="cvSection personalDetails" id="personaldetails">
          <div className="contact" id="email">
            <span>Email: </span><span>anton.riccelli@gmail.com</span>
          </div>
        </address>
      </section>
      <section className="cvSection summary" id="summary">
        <h2>Summary</h2>
        <p>
          I&apos;m an ambitious and self-motivated individual looking to transition
          to a career in the tech industry.<br />
          I have experience collaborating with teams at an international level
          and being a key stakeholder in digitalisation and process improvement
          projects.
        </p>
      </section>

      <section className="cvSection techStack" id="techstack">
        <h2>Technologies</h2>
        <ul>
          <li>HTML</li>
          <li>CSS</li>
          <li>JavaScript</li>
          <li>React.js</li>
          <li>PostgreSQL</li>
          <li>Node.js</li>
          <li>Express.js</li>
          <li>MongoDB</li>
          <li>Jest</li>
          <li>Redux</li>
          <li>AWS</li>
        </ul>
      </section>

      <section className="cvSection projects" id="projects">
        <h2>Projects</h2>
        <div className="project">
          <h3>Xpeerience - School Of Code final group project</h3>
          <a href="https://xpeerience.netlify.app/" target="_blank" rel="noreferrer" className="projectLink">Link</a>
          <p className="projectDescription">Full stack app built in a team of six as final four-week project, using React, CSS,
            MongoDB, Mongoose, following Agile methodology.</p>
        </div>

        <div className="project">
          <h3>Fight For Apollo</h3>
          <a href="https://fight-for-apollo.netlify.app/" rel="noreferrer" target="_blank" className="projectLink">Link</a>
          <p className="projectDescription">A Tic Tac Toe game with a personal touch, based on the movie Rocky IV.</p>
        </div>

        <div className="project">
          <h3>Markdown Previewer</h3>
          <a href="https://markdown-previewer-reactjs-fcc.netlify.app/"  rel="noreferrer" target="_blank" className="projectLink">Link</a>
          <p className="projectDescription">Built using React and CSS.</p>
        </div>

        <div className="project">
          <h3>Exercise Tracker</h3>
          <a href="https://fcc-exercise-trackr.herokuapp.com/"  rel="noreferrer" target="_blank" className="projectLink">Link</a>
          <p className="projectDescription">Built using React, CSS, Node.js/Express.js and MongoDB.</p>
        </div>
      </section>

      <section className="cvSection education" id="education">
        <h2>Education</h2>

        <div className="education">
          <h3>School Of Code</h3>
          <h4>Full Stack Development Bootcamp</h4>
          <p>2021 - 2022</p>
        </div>

        <div className="education">
          <h3>Naples Eastern University</h3>
          <h4>Bachelor&apos;s Degree in Foreign Languages and Literatures</h4>
          <p>2011 - 2015</p>
        </div>
      </section>

      <section className="cvSection certifications" id="certifications">
        <h2>Certifications</h2>

        <div className="certification">
          <h3>Responsive Web Design</h3>
          <h4>freeCodeCamp</h4>
          <a href="https://www.freecodecamp.org/certification/antonioriccelli/responsive-web-design"  rel="noreferrer" className="projectLink" target="_blank">Link</a>
        </div>

        <div className="certification">
          <h3>JavaScript Algorithms and Data Structures</h3>
          <h4>freeCodeCamp</h4>
          <a href="https://www.freecodecamp.org/certification/antonioriccelli/javascript-algorithms-and-data-structures"  rel="noreferrer" className="projectLink" target="_blank">Link</a>
        </div>

        <div className="certification">
          <h3>Front End Development Libraries</h3>
          <h4>freeCodeCamp</h4>
          <a href="https://www.freecodecamp.org/certification/antonioriccelli/front-end-development-libraries"  rel="noreferrer"  className="projectLink" target="_blank">Link</a>
        </div>

        <div className="certification">
          <h3>Back End Development and APIs</h3>
          <h4>freeCodeCamp</h4>
          <a href="https://www.freecodecamp.org/certification/antonioriccelli/back-end-development-and-apis"  rel="noreferrer" className="projectLink" target="_blank">Link</a>
        </div>

        <div className="certification">
          <h3>Certified Cloud Practitioner</h3>
          <h4>Amazon Web Services</h4>
          <a href="https://www.credly.com/badges/17da2ac2-f2b8-4489-9916-8a8cfc212ca3?source=linked_in_profile"  rel="noreferrer" className="projectLink" target="_blank">Link</a>
        </div>
      </section>

      <section className="cvSection workExperience" id="workexperience">
        <h2>Work Experience</h2>
        <div className="work">
          <h3>Supply Chain Planner</h3>
          <h4>Britannia Pharmaceuticals</h4>
          <p>2021</p>
        </div>

        <div className="work">
          <h3>Supply Chain Analyst</h3>
          <h4>Ashfield Healthcare UDG</h4>
          <p>2019 - 2021</p>
        </div>

        <div className="work">
          <h3>Customer Service Executive</h3>
          <h4>Ashfield Healthcare UDG</h4>
          <p>2018 - 2019</p>
        </div>

        <div className="work">
          <h3>Moment Banker</h3>
          <h4>Barclays Bank</h4>
          <p>2017 - 2018</p>
        </div>

        <div className="work">
          <h3>Essential Banker</h3>
          <h4>Barclays Bank</h4>
          <p>2016 - 2017</p>
        </div>

        <div className="work">
          <h3>Barista</h3>
          <h4>Costa Coffee</h4>
          <p>2015 - 2016</p>
        </div>
      </section>
    </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
