name: Build Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run:  npm ci

      - name: Build Next.js app
        run: |
          npm run build
          npm run export

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generated-files
          path: ./out          

      - name: Commit and Push changes
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Deploy generated files"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: $({ secrets.GITHUB_TOKEN })