name: Build Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run:  npm install

      - name: Build Next.js app
        run: |
          npm run build
          npm run export

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_dir
          path: out/        
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build_dir
          path: out/
      - name: Test artifact download
        run: ls -R
      - name: Commit and Push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Merge artifacts"
          git push

      # - name: Commit and Push changes
      #   run: |
      #     git config --global user.email "no-reply@github.com"
      #     git config --global user.name "GitHub Action"
      #     git add .
      #     git commit -m "Deploy generated files"
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      #     git push
      #   env:
      #     GITHUB_TOKEN: $({ secrets.GITHUB_TOKEN })

      # - name: Add & Commit
      #   uses: EndBug/add-and-commit@v9.1.3
      #   with:
      #     add: '.'
